[package]
name = "stringliner"
version = "0.1.1"
authors = ["Markus Hihn <0mbi@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
